# Generated by Django 4.2.4 on 2023-09-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verificated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Верифицирован'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Токен'),
        ),
    ]
